### ISSUE TITLE
Had trouble compiling on 4.6 kernel

### ISSUE THREAD

**Issue by sautingleung** [ondr3j/paragon-ufsd#1]
Hi, I had trouble compiling your code on a 4.6 kernel. The foloowing is how I fixed it and finally compiled.

kernel function rename:

> page_cache_release -> put_page
> page_cache_get -> get_page
> PAGE_CACHE_\* -> PAGE_*
> get_user_pages() ->  get_user_pages_remote()

**Comment by ondr3j** [comment]
Interesting. Which release of the 4.6 kernel are you using?

**Comment by sautingleung** [comment]
My OS is Ubuntu 16.04. I downloaded the 4.6.2-040602-generic kernel and headers for amd64 from ubuntu's mainline ppa http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.6.2-yakkety/. Your code would not compile on this kernel. Searching with google I found http://www.spinics.net/lists/reiserfs-devel/msg05026.html and https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7. With this info I was able to hack ufsdvfs.c and ufsdjnl.c to get it to compile. I have attached those files for your perusal. Checkout http://lxr.free-electrons.com/ident?i=page_cache_get on the 4.6 kernel and see that page_cache_get is no longer in the 4.6 kernels. It surprises me you were able to compile your code on any 4.6 kernel.

Hope that helps. Please email again if you have any further questions.

[https://1.gravatar.com/avatar/21d8688519139de91ec825d5f83ff69f?d=https%3A%2F%2Fassets-cdn.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png&r=x&s=200]https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7

mm/gup: Introduce get_user_pages_remote() · torvalds/linux@1e98779https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7
github.com
For protection keys, we need to understand whether protections should be enforced in software or not. In general, we enforce protections when working on our own task, but not when on others. We ca...

Re: [PATCH] reiser4: port for linux-4.6 (Reiser Filesystem Devel)http://www.spinics.net/lists/reiserfs-devel/msg05026.html
www.spinics.net
Reiser Devel: Re: [PATCH] reiser4: port for linux-4.6

https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7

[https://1.gravatar.com/avatar/21d8688519139de91ec825d5f83ff69f?d=https%3A%2F%2Fassets-cdn.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png&r=x&s=200]https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7

mm/gup: Introduce get_user_pages_remote() · torvalds/linux@1e98779https://github.com/torvalds/linux/commit/1e9877902dc7e11d2be038371c6fbf2dfcd469d7
github.com
For protection keys, we need to understand whether protections should be enforced in software or not. In general, we enforce protections when working on our own task, but not when on others. We ca...

**Comment by nirvam** [comment]
Same issue here. Was installing your AUR package paragon-ufsd-dkms-git on Arch Linux for 4.6.2-1-ARCH and 4.5.7-1-ck. Module compiling for 4.5.7-1-ck succeeded while 4.6.2-1-ARCH failed. DKMS make.log attached.
[make.log.zip](https://github.com/ondr3j/paragon-ufsd/files/331541/make.log.zip)

**Comment by ondr3j** [comment]
Applied changes in 2ff11e540d0e06f45149edc12c8141cfe191039d. Thanks guys. I will be closing this issue, all should be well now.
